### PR TITLE
Fix cpants issues

### PR DESCRIPTION
**Pull request by manwar**
Hi Gabor,

As part of PRC 2017, this is my Jan 2017 pull request. 
Please review the PR. 
It try to address issues raised by CPANTS. Also cpantester failed report.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by szabgab** [comment]
Can I just pass the whole distribution to you? Would that still count in the PRC?

**Comment by manwar** [comment]
Hi Gabor,

I am not sure, whether it still counts or not, honestly speaking.
However you can merge my pull request if you are happy with my proposed changes. 
And then you can transfer the distribution, if you like. 
I will never say "No" to such request, you know my weakness. 

Best Regards,
Mohammad S Anwar

**Comment by szabgab** [comment]
great. merged. Please remove the fork you have in GitHub and then I'll transfer the repo.

**Comment by manwar** [comment]
Removed the fork.
Thanks

**Pull request merged**
